function results = run_tests(varargin)
%RUN_TESTS   Run all mip unit tests.
%
% Usage:
%   results = run_tests();
%   results = run_tests('Coverage', true);
%
% Name-Value Arguments:
%   Coverage - Enable code coverage reporting (default: false).
%              Generates coverage.xml (Cobertura format) in the repo root.
%
% Returns:
%   results - TestResult array from MATLAB's testing framework

import matlab.unittest.TestSuite
import matlab.unittest.TestRunner
import matlab.unittest.plugins.DiagnosticsValidationPlugin

% Parse optional arguments
p = inputParser;
addParameter(p, 'Coverage', false, @islogical);
parse(p, varargin{:});

% Get the directory containing this script
testDir = fileparts(mfilename('fullpath'));
repoRoot = fileparts(testDir);

% Add repo root, test dir, and helpers to path (repo root must be first
% so the correct +mip package is found regardless of current directory)
helpersDir = fullfile(testDir, 'helpers');
addpath(repoRoot);
addpath(testDir);
addpath(helpersDir);

% Restore path on exit
cleanupObj = onCleanup(@() rmpath(helpersDir, testDir, repoRoot));

% Build test suite from explicit test classes
suite = [ ...
    TestSuite.fromClass(?TestUtilsParsing), ...
    TestSuite.fromClass(?TestNameEquivalence), ...
    TestSuite.fromClass(?TestNameVariants), ...
    TestSuite.fromClass(?TestParseYaml), ...
    TestSuite.fromClass(?TestMipRoot), ...
    TestSuite.fromClass(?TestKeyValueStorage), ...
    TestSuite.fromClass(?TestPackageDiscovery), ...
    TestSuite.fromClass(?TestReadMipYaml), ...
    TestSuite.fromClass(?TestLoadPackage), ...
    TestSuite.fromClass(?TestUnloadPackage), ...
    TestSuite.fromClass(?TestLoadAddpathRmpath), ...
    TestSuite.fromClass(?TestLoadWithExtraPaths), ...
    TestSuite.fromClass(?TestInstallExtraPaths), ...
    TestSuite.fromClass(?TestMipIdentity), ...
    TestSuite.fromClass(?TestInstallLocal), ...
    TestSuite.fromClass(?TestUninstallPackage), ...
    TestSuite.fromClass(?TestUninstallSelf), ...
    TestSuite.fromClass(?TestInfoPackage), ...
    TestSuite.fromClass(?TestInfoSelf), ...
    TestSuite.fromClass(?TestUpdateLocal), ...
    TestSuite.fromClass(?TestUpdateBranchOrVersion), ...
    TestSuite.fromClass(?TestCompile), ...
    TestSuite.fromClass(?TestSelectBestVersion), ...
    TestSuite.fromClass(?TestCompareVersions), ...
    TestSuite.fromClass(?TestSelectBestVariant), ...
    TestSuite.fromClass(?TestBundleCommand), ...
    TestSuite.fromClass(?TestInit), ...
    TestSuite.fromClass(?TestInstallPromptInit), ...
    TestSuite.fromClass(?TestInstallZipUrl), ...
    TestSuite.fromClass(?TestListCommand), ...
    TestSuite.fromClass(?TestIndexUrl), ...
    TestSuite.fromClass(?TestTestCommand), ...
    TestSuite.fromClass(?TestBrokenDependencyWarning), ...
    TestSuite.fromClass(?TestMatchBuild), ...
    TestSuite.fromClass(?TestResetCommand), ...
    TestSuite.fromClass(?TestDownloadMhl), ...
    TestSuite.fromClass(?TestExtractMhl), ...
    TestSuite.fromClass(?TestFetchIndexCache), ...
    TestSuite.fromClass(?TestPinPackage), ...
    TestSuite.fromClass(?TestInstallEquivalentFqn), ...
    TestSuite.fromClass(?TestInstallMhl), ...
    TestSuite.fromClass(?TestFunctionSignatures), ...
    TestSuite.fromClass(?TestFindAllDependencies), ...
    TestSuite.fromClass(?TestPathTraversal), ...
];

% Add remote/channel tests unless MIP_SKIP_REMOTE is set
if isempty(getenv('MIP_SKIP_REMOTE'))
    suite = [suite, ...
        TestSuite.fromClass(?TestInstallRemote), ...
        TestSuite.fromClass(?TestUpdateRemote), ...
        TestSuite.fromClass(?TestUpdateSelf), ...
        TestSuite.fromClass(?TestInstallRemoteAdvanced), ...
        TestSuite.fromClass(?TestFetchIndexCacheRemote)];
end

% Run tests
runner = TestRunner.withTextOutput('Verbosity', 3);

% Add coverage plugins if requested
if p.Results.Coverage
    import matlab.unittest.plugins.CodeCoveragePlugin
    import matlab.unittest.plugins.codecoverage.CoberturaFormat
    import matlab.unittest.plugins.codecoverage.CoverageReport

    sourceFolder = fullfile(repoRoot, '+mip');
    coverageFile = fullfile(repoRoot, 'coverage.xml');
    coverageDir = fullfile(repoRoot, 'coverage-report');
    runner.addPlugin(CodeCoveragePlugin.forFolder(sourceFolder, ...
        'IncludingSubfolders', true, ...
        'Producing', [CoberturaFormat(coverageFile), ...
                      CoverageReport(coverageDir)]));
    fprintf('Code coverage enabled.\n');
    fprintf('  Cobertura XML: %s\n', coverageFile);
    fprintf('  HTML report:   %s\n', fullfile(coverageDir, 'index.html'));
end

results = runner.run(suite);

% Print summary
fprintf('\n=== Test Summary ===\n');
fprintf('  Total:   %d\n', length(results));
fprintf('  Passed:  %d\n', sum([results.Passed]));
fprintf('  Failed:  %d\n', sum([results.Failed]));
fprintf('  Errors:  %d\n', sum([results.Incomplete]));

if all([results.Passed])
    fprintf('\nAll tests passed.\n');
else
    fprintf('\nSome tests failed. See details above.\n');
    % Print failed test names
    failedIdx = find(~[results.Passed]);
    for i = 1:length(failedIdx)
        fprintf('  FAILED: %s\n', results(failedIdx(i)).Name);
    end
end

end
